site_name: Bruno News
site_url: https://mydomain.org/Bruno News
theme:
  name: material
  palette:
    scheme: slate
    primary: deep-purple
    accent: green
  font:
    text: roboto
    code: roboto-mono

plugins:
  - blog
